// angular/docs/src/app/getting-started/dark-mode/dark-mode.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dark-mode',
  templateUrl: './dark-mode.component.html',
  styleUrls: ['./dark-mode.component.scss']
})
export class DarkModeComponent implements OnInit {
  code1 = `/* You can add global styles to this file, and also import other style files */
// @import "./assets/sass/style";

// Replace above style with this SCSS file to enable dark mode styles
@import "./assets/sass/style.dark";
`;

  code2 = `// @import "./assets/sass/style";`;

  code3 = `@import "./assets/sass/style.dark";`;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="pb-10">
  <h1 class="anchor fw-bolder mb-5" id="deployment">
    <a href="#deployment"></a>Quick Setup
  </h1>

  <div class="py-5">
    <p class="mb-0">Metronic supports full <b>Dark Mode</b> and easily setup following the below instructions.</p>
  </div>

  <div class="py-5">
    <ol class="my-0 py-0">
      <li class="py-3">
        Open file <code>demo1/src/styles.scss</code>

        <app-code-block language="scss" [code]="code1"></app-code-block>
      </li>

      <li class="py-3">
        Comment this line to disable <code>style.scss</code> from being loaded

        <app-code-block language="scss" [code]="code2"></app-code-block>
      </li>

      <li class="py-3">
        Uncomment this line to to load <code>style.dark.scss</code>

        <app-code-block language="scss" [code]="code3"></app-code-block>
      </li>
    </ol>
  </div>
</div>

// react/docs/src/app/gettings-started/DarkMode.tsx
/* eslint-disable jsx-a11y/anchor-has-content */
import React from 'react'
import {CodeBlock} from '../../_metronic/partials'

export function DarkMode() {
  return (
    <>
      <h1 className='anchor fw-bolder mb-5' id='quick_setup'>
        <a href='#quick_setup'></a>
        Quick Setup
      </h1>

      <div className='pt-4'>
        Metronic supports full <b>Dark Mode</b> that you can easily setup following the below
        instructions.
      </div>

      <ol className='pt-4'>
        <li>
          In file <code>demo1/src/index.tsx</code> replace main scss file to dark mode.
          <CodeBlock language='scss' code={styleCode} />
        </li>
        <li>
          In file <code>demo1/public/index.html</code> add dark-mode class name to the{' '}
          <code>&lt;body&gt;</code> tag.
          <CodeBlock language='markdown' code={htmlCode} />
        </li>
      </ol>
    </>
  )
}

const styleCode = `- import './_metronic/assets/sass/style.scss'
+ import './_metronic/assets/sass/style.dark.scss'`

const htmlCode = `<body class="dark-mode ...">
<!-- HTML content -->
</body>`
